"""Contract test for the stable Stage 2 reconstruction API fixture.

``tests/fixtures/reconstruction_response.json`` is a real, ID-normalized
snapshot of a live POST /api/incidents/{id}/reconstruct response (plus its
companion timeline/relationships/episodes/records endpoints), generated by
``tests/fixtures/generate_reconstruction_fixture.py``. The frontend uses this
same file as mock data for Stage 2B component tests.

This test asserts the fixture's shape matches what the backend actually
returns today, so frontend contract tests built against it stay honest —
if the backend response shape changes, this test (and the frontend tests
built on the same fixture) should fail loudly rather than silently drift.
"""

from __future__ import annotations

import json
from pathlib import Path

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "reconstruction_response.json"


def _load_fixture() -> dict:
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def test_fixture_file_exists_and_parses():
    assert FIXTURE_PATH.exists()
    data = _load_fixture()
    assert isinstance(data, dict)


def test_fixture_top_level_shape():
    data = _load_fixture()
    for key in ("incident_id", "upload", "incident", "reconstruction", "reconstructions", "timeline", "relationships", "episodes", "records"):
        assert key in data, f"missing top-level key: {key}"


def test_fixture_reconstruction_shape_matches_reconstruction_to_dict():
    from webapp.api.incidents.models import Reconstruction

    data = _load_fixture()
    recon = data["reconstruction"]

    # Every field on the dataclass's to_dict() must be present in the fixture
    # (plus the router's added timeline/relationships/episodes expansion).
    dummy = Reconstruction(reconstruction_id="x", incident_id="y")
    for key in dummy.to_dict():
        assert key in recon, f"reconstruction fixture missing field: {key}"

    for key in ("timeline", "relationships", "episodes"):
        assert key in recon, f"reconstruction fixture missing expanded field: {key}"


def test_fixture_alignment_shape():
    from webapp.api.incidents.models import AlignmentAssessment

    data = _load_fixture()
    alignment = data["reconstruction"]["alignment"]
    dummy = AlignmentAssessment()
    for key in dummy.to_dict():
        assert key in alignment, f"alignment fixture missing field: {key}"


def test_fixture_episode_shape():
    from webapp.api.incidents.models import FaultEpisode

    data = _load_fixture()
    assert data["episodes"], "fixture must contain at least one episode"
    dummy = FaultEpisode(episode_id="x", incident_id="y")
    for episode in data["episodes"]:
        for key in dummy.to_dict():
            assert key in episode, f"episode fixture missing field: {key}"


def test_fixture_relationship_shape():
    from webapp.api.incidents.models import RecordRelationship

    data = _load_fixture()
    assert data["relationships"], "fixture must contain at least one relationship"
    dummy = RecordRelationship(relationship_id="x", incident_id="y", left_record_id="a", right_record_id="b")
    for rel in data["relationships"]:
        for key in dummy.to_dict():
            assert key in rel, f"relationship fixture missing field: {key}"


def test_fixture_timeline_event_shape():
    from webapp.api.incidents.models import IncidentTimelineEvent

    data = _load_fixture()
    assert data["timeline"], "fixture must contain at least one timeline event"
    dummy = IncidentTimelineEvent(timeline_event_id="x", incident_id="y")
    for event in data["timeline"]:
        for key in dummy.to_dict():
            assert key in event, f"timeline event fixture missing field: {key}"


def test_fixture_physical_cause_evidence_has_audit_fields():
    """Guards the item-3 stabilization: stored cause evidence must carry the
    full audit trail (model_version, feature_version, calibration, timing,
    raw/calibrated probabilities, applied caps) — not just a bare label."""
    data = _load_fixture()
    physical_cause = data["reconstruction"]["physical_cause_evidence"]
    assert physical_cause["scope"] == "RECORD_LOCAL_SIGNATURES"
    assert physical_cause["incident_root_cause"] == "UNCONFIRMED"
    assert physical_cause["records"], "fixture must contain per-record cause evidence"

    for record_entry in physical_cause["records"]:
        for field in (
            "analysis_id", "incident_record_id", "top_hypothesis", "confidence",
            "cause_ranking", "model_version", "feature_version", "calibration_method",
            "timing_source", "raw_probabilities", "calibrated_probabilities", "applied_caps",
        ):
            assert field in record_entry, f"physical_cause_evidence record missing field: {field}"

        # cause_ranking[0]'s confidence must match the capped top-level
        # confidence (regression guard for the ranking/confidence cap
        # consistency fix applied in ml_predict.py).
        if record_entry["cause_ranking"]:
            assert record_entry["confidence"] == record_entry["cause_ranking"][0]["confidence"]


def test_fixture_no_probability_averaging_field():
    """There must be no incident-level combined-probability field anywhere —
    only per-record entries plus a qualitative consistency label."""
    data = _load_fixture()
    physical_cause = data["reconstruction"]["physical_cause_evidence"]
    assert "incident_probability" not in physical_cause
    assert "average_confidence" not in physical_cause
    assert physical_cause["consistency"] in ("CONSISTENT", "MOSTLY_CONSISTENT", "MIXED", "CONTRADICTORY", "INSUFFICIENT")
