import type {
  FaultEpisodeOut,
  IncidentOut,
  IncidentRecordOut,
  IncidentTimelineEventOut,
  ReconstructionOut,
  RecordRelationshipOut,
} from "../../api/client";
import raw from "./reconstruction_response.json";

/**
 * Stable, ID-normalized snapshot of a real Stage 2 reconstruction API
 * response, generated by tests/fixtures/generate_reconstruction_fixture.py
 * (Python backend) and copied here so frontend contract tests exercise the
 * exact shape the backend actually returns rather than a hand-written guess.
 */
export function loadReconstructionFixture() {
  const data = raw as unknown as {
    incident_id: string;
    incident: IncidentOut;
    reconstruction: ReconstructionOut;
    reconstructions: ReconstructionOut[];
    timeline: IncidentTimelineEventOut[];
    relationships: RecordRelationshipOut[];
    episodes: FaultEpisodeOut[];
    records: IncidentRecordOut[];
  };
  return data;
}
